### ISSUE TITLE
🚀 Feature Request: diversifying website...

### ISSUE THREAD

**Issue by Salazareo** [utm-cssc/website#100]
### Problem Overview 👁️‍🗨️

I think this is a great idea to help showcase student projects, however it does feel, for lack of a better word, biased towards someone/ some group. This is specially apparent giving grey software takes precedence over student projects...

### What would you like? 🧰

Well firstly maybe a reorganization to really prop up student and utm projects, and feel less biased.
Secondly, I think adding a feature to submit addition requests through the website would also help with this. 
A form perhaps so say, a 490 group just finished a cool project meant to help UofT students, perhaps something like https://www.uoftea.ca :^) and they want more people to hear about it and hopefully help them. A form would help with that, and with diversifying the site.

### What alternatives have you considered? 

Not using this site

### Additional details ℹ️

Plz also add uoftea.ca on there ye?

**Comment by ArsalaBangash** [comment]
Anyone can add projects @Salazareo, and I encourage you to do so in order to correct the bias :)
