### ISSUE TITLE
🐛 Bug: {{CSC290 course description wrong}}

### ISSUE THREAD

**Issue by MichaelGitHubHype** [utm-cssc/website#101]
### Expected Behavior 🧭

CSC290 course description should be "Communication Skills for Computer Scientists"

### Current Behavior 🔍 
Currently says: "Data Structures and Analysis"

### Steps to Reproduce 🔢 

1. Go here: https://cssc.utm.utoronto.ca/resources/
2. Hover "CSC290"

**Comment by hiimchrislim** [comment]
Great catch! Fixed.
