### ISSUE TITLE
🚀 Feature Request: Display Club Events on Calendar

### ISSUE THREAD

**Issue by CometWhoosh** [utm-cssc/website#170]
### Problem Overview 👁️‍🗨️

It would be helpful to display hexagon club events in the calendar so that students can easily see what events are taking place in the MCS department.

### What would you like? 🧰

We can create a google form that hexagon clubs can fill out to add their event to our calendar. Then, we can get the data from the form responses and parse it to add the events to the calendar.

**Comment by AipioxTechson** [comment]
Done!
