### ISSUE TITLE
🐛 Bug: Ask Jack HTTP 500 error

### ISSUE THREAD

**Issue by ggggg** [utm-cssc/website#221]
### Expected Behavior 🧭

The page ask-jack should render

### Current Behavior 🔍 

The server responds with an HTTP 500 error

### Steps to Reproduce 🔢 

(Please write your answer here.)

1. Go to the live website (https://cssc.utm.utoronto.ca/)
2. Click "Ask Jack"

**Acceptence Criteria for Fix ✅**

- [ ] The Ask Jack page renders with a 2XX HTTP status

### Possible Solution 🛠️ 

Need to investigate further

**Implementation Details 🧰**

**Comment by huonggiangbui** [comment]
Should be resolved by now
