### ISSUE TITLE
Improve responsive design issues on the website

### ISSUE THREAD

**Issue by ArsalaBangash** [utm-cssc/website#32]
- [x] Make the navbar responsive (mentioned by @hiimchrislim and @ArsalaBangash  in the comments)
- [x] Modify font sizes for smaller screens
- [x] Fix overflow of text in the resource grid
- [x] FIx Arrow overlap in Hero Component

**Comment by ArsalaBangash** [comment]
![image](https://user-images.githubusercontent.com/19757203/93022125-44c70200-f5b5-11ea-9c47-08f0d4d639e0.png)

**Comment by hiimchrislim** [comment]
Resource item title overflowing onto another box
![image](https://user-images.githubusercontent.com/24628243/93022178-b56e1e80-f5b5-11ea-8576-f6c38ea96fcb.png)

**Comment by hiimchrislim** [comment]
With a smaller screen size, the navbar links disappear. 
If you still click around the area where the links disappear, you can still go to the resources page

![image](https://user-images.githubusercontent.com/24628243/93022274-7f7d6a00-f5b6-11ea-80db-546305a24a07.png)

**Comment by milindvishnoi** [comment]
![image](https://user-images.githubusercontent.com/48028572/93026855-b4290a00-f626-11ea-9dfc-df833b2ac51b.png)

**Comment by hiimchrislim** [comment]
On an iPad display, the arrow is at the very bottom. I think it should be somewhat under the Tech of the Month and the MCS Orientation EKit Button
![image](https://user-images.githubusercontent.com/24628243/93027484-270c9380-f5db-11ea-9894-af4bd9854f7c.png)

**Comment by milindvishnoi** [comment]
@hiimchrislim and @ArsalaBangash I have fixed all the CSS issues mentioned above. 

Please let me know if there are any other issues otherwise, you can go ahead and close this issue.
