### ISSUE TITLE
Conduct an accessibility audit for the website

### ISSUE THREAD

**Issue by ArsalaBangash** [utm-cssc/website#34]

**Comment by ArsalaBangash** [comment]
@ZainHKazmi pleade post the audit results here and begin a discussion about how we can tackle the issues that emerge

**Comment by ZainHKazmi** [comment]
@ArsalaBangash @hiimchrislim Accessibility audit results: https://docs.google.com/document/d/1k2rHMP7qe1KvObonT71Dr71q9SDf_x-WoYVyAkrWcXA/edit#

**Comment by jcserv** [comment]
Closing as we've done an updated accessibility audit.
