### ISSUE TITLE
Add a Unified Events Calendar to the Website

### ISSUE THREAD

**Issue by hiimchrislim** [utm-cssc/website#36]
# Overview

Students at UTM have never had a global view into the events happening across our hexagon clubs. This feature is designed to fix that. 

# Purpose

# Technical Checklist

- [x] Finding a vue calendar component
- [x] Using nuxt content
- [x] Each club submits a CSV (A club rep would have push access to add their content)

# Expected Timeline

Note: Email Andrew Wang for unified calendar for the rest of the students

**Comment by ArsalaBangash** [comment]
If the clubs are using Google calendar or Microsoft Outlook, they can export their calendars to ics, we can convert them to a csv using [this](https://www.projectwizards.net/en/support/ics2csv-converter), and then parse them into a calendar component such as [this](https://vuetifyjs.com/en/components/calendars/)

**Comment by ArsalaBangash** [comment]
Before any technically overhauled solution, I encourage us to go with something simple where we can manually look for events.

**Comment by hiimchrislim** [comment]
The following are the events that I was able to find for the rest of the MCS clubs
Robotics: https://utmrobotics.com/events
WISC: https://www.wiscutm.com/events/
UTMSAM: http://utmsam.sa.utoronto.ca/future-events/
DSC: N/A
MCSS: N/A

**Comment by milindvishnoi** [comment]
@hiimchrislim and I discussed another way for making this calendar where we use a JS script to get data from another repo (we created a repo to the csv/isv files from check it out by clicking [here](https://github.com/utm-cssc/unified-calendar-data)).

### The main advantages for this way are:
- We don't have to give permission to push to our repo (ensures no club accidentatly changes our website)

### Variables needed for creating event in the calendar
- name
- description
- start date
- start time
- end date
- end time

**Comment by hiimchrislim** [comment]
Current progress of the calendar
Note: The events are randomly generated, but the colors for the particular clubs are correct
![image](https://user-images.githubusercontent.com/24628243/93538503-4594c680-f91c-11ea-9284-5ce357916b2d.png)

**Comment by hiimchrislim** [comment]
Current state of the unified calendar
![image](https://user-images.githubusercontent.com/24628243/93715675-b4e70200-fb38-11ea-9d41-00ca9fcb7244.png)

Reiterating the previous things to improve on + more
- [ ] The menu for switching between different views (month/weekly/daily, etc.) doesn't work
- [ ] The ending time for an event should be displayed rather than just the starting time
- [ ] Creating a script to obtain the CSV's

**Comment by milindvishnoi** [comment]
@hiimchrislim Made separate files for each club to display events. 

Although making the ending time display may not be possible from this component. If you find anything for displaying ending time in the calendar please let me know.

**Comment by milindvishnoi** [comment]
@ArsalaBangash Will you give a more comprehensive review or should I just make these changes?
