### ISSUE TITLE
Issue/Feature/PR Templates

### ISSUE THREAD

**Issue by hiimchrislim** [utm-cssc/website#39]
- [x] Bug Report Template
- [x] Feature Request Template
- [x] Maintenance Template

**Comment by hiimchrislim** [comment]
---
name: "Task Name"
owners: "Who does this task belong to?"
---

## Task Information

**❓About**
What is this task about and why is it useful to have this on our website?

 

**🗓️ Timeline**
Provide a rough estimate as to how long it'll take to complete this task and describe the objectives/goals for each week.

 

**🛠️ Responsibilities **
If you have 1 or more members working on this task, what will each of them be doing?

Proposed task template

**Comment by ArsalaBangash** [comment]
# Proposed Bug Template 



# Expected Behavior


### Acceptence Criteria


- [ ] 
- [ ] 
- [ ] 

# Current Behavior


# Possible Solution


### Implementation Details


# Steps to Reproduce


1.
2.
3.
4.


## Additional details

**Comment by ArsalaBangash** [comment]
Hi Chris, I was thinking that since a task can be a bug, a feature, or a maintenance task, we could just create templates for those three and encompasses them all under a task. In the future, they wouldn't only be task templates, because you could have discussion templates
'

**Comment by hiimchrislim** [comment]
I see, yea that makes sense!

**Comment by ArsalaBangash** [comment]
# Proposed Feature Request Template 

### Problem Overview 👁️‍🗨️ 



(Write your answer here.)

### Describe what you'd like 🧰



(Describe your proposed solution here.)

### Describe alternatives you've considered 🔍



(Write your answer here.)

### Additional details ℹ️



(Write your answer here.)

**Comment by ArsalaBangash** [comment]
# Code Refactor Task proposal

### Motivation 🏁



(Write your motivation here.)

### Describe your refactoring solution 🛠️ 



(Describe your proposed solution here.)

### Additional details ℹ️



(Write your answer here.)

**Comment by ArsalaBangash** [comment]
# Proposed Initiative Template 

### Motivation 🏁



### Initiative Overview 👁️‍🗨️ 



### Possible Solution 🛠️ 


(Write your answer here.)


**Execution Details 🧰**


(Write your answer here.)


- 
- 
- 


### Describe alternatives you've considered 🔍



(Write your answer here.)

### Additional details ℹ️



(Write your answer here.)

**Comment by ArsalaBangash** [comment]
I have setup Issue and Feature Request templates

**Comment by ArsalaBangash** [comment]
The first iterations for these issue templates have been setup
