### ISSUE TITLE
Create first draft of CSSC Landing page

### ISSUE THREAD

**Issue by ArsalaBangash** [utm-cssc/website#4]

**Comment by milindvishnoi** [comment]
@hiimchrislim Please attach the Adobe Design link.

**Comment by hiimchrislim** [comment]
I can't attach .xd files here (Github doesn't support that file type)
However, it can be found in the Tech Team Channel (in the UTM CSSC: Internal Team)

**Comment by milindvishnoi** [comment]
Just updating you all on what I have work on so far. @ArsalaBangash and I will work on CSSC page further so I'll upload the progress then once again.

Hero Page
![image](https://user-images.githubusercontent.com/48028572/91151075-d0e2b980-e6da-11ea-89e9-425502aa6a70.png)

What is CSSC Section?
![image](https://user-images.githubusercontent.com/48028572/91151136-ebb52e00-e6da-11ea-9dc7-417a07e9ac6d.png)

**Comment by hiimchrislim** [comment]
Good to have:
- Logo with 1x3 component right underneath (See utmhacklab.tech for layout)
- Text size should be smaller (I made a few changes previously, but it's still a bit large)
- Make headings and subheadings responsive
- "How to contribute" layout should be the same as the current Hacklab website (for now)

**Comment by hiimchrislim** [comment]
- [ ] I think it would be good to have the bouncing arrow clickable where if it's clicked, it'll scroll to the 1x3 Grid

**Comment by ArsalaBangash** [comment]
Grid1x2
title=Our History
desc=The CSSC was born out of the Hacklab a department initiative that brought together all 6 UTM clubs in DH2014. 
image=Hacklab logo
link=utmhacklab.tech
