### ISSUE TITLE
🐛 Bug: Live Data Not Propagated

### ISSUE THREAD

**Issue by hiimchrislim** [utm-cssc/website#53]
### Expected Behavior 🧭

When updating any CSV on the FAQ or UnifiedCalendar repo, the changes should be propagated to the live website.

### Current Behavior 🔍 

The current state of the FAQ and UnifiedCalendar are based on the current data on the website re-compile time. When the website gets compiled, the pages directly get served from dist/.

**Acceptence Criteria for Fix ✅**
The new data should automatically be propagated

### Possible Solution 🛠️ 

I believe there are some settings to change the way we compile the content when serving it

**Update** : When updating the Github FAQ/Unified Calendar Content Repository, Github caches the information for 5 minutes and the new data won't be shown until 5 minutes later. It could be possible that this is a Github thing and the website might be fine

**Comment by milindvishnoi** [comment]
I don't think this bug actually exists because I can see all the live refreshes currently on the website.

**Comment by hiimchrislim** [comment]
Are you able to make a Loom Video to show how the live refreshes on your end?
I just tried to update the CSV for the FAQ and for the calendar and the live website doesn't seem to update at all

**Comment by ArsalaBangash** [comment]
This issue will probably be resolved when we can use server-side-rendering from our MCS server.

**Comment by ArsalaBangash** [comment]
Email Andrew Wang about the server
