### ISSUE TITLE
🚀 Feature Request: Past Leadership Page

### ISSUE THREAD

**Issue by hiimchrislim** [utm-cssc/website#54]
### Problem Overview 👁️‍🗨️ 

We should display the past mentors/leaders from previous years

### What would you like? 🧰

A new page displaying the the past mentors/leaders. It should be similar to the "Meet the team" section including their name, image, description and methods of contact.

I think it would be good if these are categorized by year of leadership

**Comment by milindvishnoi** [comment]
This section can use the setup I created for the team component on [this](https://github.com/utm-cssc/website/pull/48). Please look at the nuxt setup which we can use to display this information.

**Comment by milindvishnoi** [comment]
@hiimchrislim Please get me the information I need to post for past leaders.
