### ISSUE TITLE
🚀 Feature Request: Component Unit Testing

### ISSUE THREAD

**Issue by hiimchrislim** [utm-cssc/website#69]
### What would you like? 🧰

We should create Unit Tests so that for any subsequent changes/additions to the website, there aren't any side effects to other components that aren't related to that subsequent change.

This will reduce any side effects as well as ensuring that our website has proper content being displayed. 

### Additional details ℹ️

A good link to check out for Vue Unit Testing: https://www.vuemastery.com/courses/unit-testing/what-to-test/

**Comment by ArsalaBangash** [comment]
This is a great tech talk https://www.youtube.com/watch?v=DD1fEhcEzY8

**Comment by ArsalaBangash** [comment]
https://www.freecodecamp.org/news/an-introduction-to-tdd-with-vue-js-66544710b50c/
