### ISSUE TITLE
🚀 Feature Request: GPA Calculator

### ISSUE THREAD

**Issue by milindvishnoi** [utm-cssc/website#76]
### Problem Overview 👁️‍🗨️
Calculating the percentage for a course can be very tedious and time-consuming.

### What would you like? 🧰
A calculator that can calculate the percentage you currently have and how much you need to get a certain grade.

**Comment by hiimchrislim** [comment]
It would be cool if we could have a login to save the previous choices that a student has chosen

**Comment by hiimchrislim** [comment]
Using cookies in place of the login for now
