### ISSUE TITLE
Add header component 

### ISSUE THREAD

**Issue by ArsalaBangash** [utm-cssc/website#8]
Add a header component that contains

- [x] Logo that links to home
- [x] Search bar that searches content
- [x] Important links (refer to utmhacklab.tech)

**Comment by hiimchrislim** [comment]
Current issues
- Responsiveness (on different screen sizes)
- Text-decoration removal

**Comment by milindvishnoi** [comment]
New Issues
- [ ] The navbar clicks when it is not open on a mobile view
