### ISSUE TITLE
Add a SearchBar component to the website

### ISSUE THREAD

**Issue by ArsalaBangash** [utm-cssc/website#9]
We should have a persistent Search Bar that allows students to search through our content

**Here's a snippet from the Nuxt Community**:
https://content.nuxtjs.org/snippets#search

**Comment by ArsalaBangash** [comment]
@milindvishnoi How's the search bar coming along? Do we have any issues with the HTML or JS?

**Comment by milindvishnoi** [comment]
@ArsalaBangash Functionality is fine. Most of HTML and CSS is okay as well.

The only issue right now with the search component is that it does not work with the keyboard inputs.

**Comment by ArsalaBangash** [comment]
Please add a PR. It may be that there's no <input> tag underneath?
